name: go project

on: pull_request

jobs:
  build-go-project:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.21.6
      uses: actions/setup-go@v5.0.0
      with:
        go-version: '1.21.6' 
    - run: go version
      
    - name: Get all dependencies based on go.mod
      run: go mod download

    - name: Build - compile Go code into executable binaries
      run: go build -v .
    
    # - name: Simulate failure
    #   run: exit 1