name: Go webapp workflow

on: pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.21.6
        uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.21.6"
      - run: go version

      - name: Get all dependencies based on go.mod
        run: go mod download

      - name: Set up environment variables
        run: echo "DB_DSN=host=localhost port=5432 user=postgres password=postgres dbname=postgres sslmode=disable" >> $GITHUB_ENV

      - name: Run integration tests
        run: go test -v ./...