name: Packer workflow

on: pull_request

env:
  PACKER_VERSION: "1.10.1"

jobs:
  packer-fmt-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Run `packer init`
        id: init
        run: packer init .

      - name: Run `packer fmt`
        id: fmt
        run: packer fmt -check .

      - name: Run `packer validate`
        id: validate
        run: packer validate .
