name: Packer workflow

on:
  pull_request:
    types:
      - closed

jobs:
  packer-build-custom-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      ENV: "github"
      GO_VERSION: "1.21.6"
      PACKER_VERSION: "1.10.1"

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into app directory
        uses: actions/checkout@v4

      - name: Set up Go 1.21.6
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go version

      - name: Get all dependencies based on go.mod
        run: go mod download

      - name: Setup github runner environment variables for integration tests
        run: |
          { 
            echo "DB_HOST=localhost"; 
            echo "DB_PORT=5432"; 
            echo "DB_USER=postgres"; 
            echo "DB_PASSWORD=postgres"; 
            echo "DB_NAME=postgres" 
          } >> $GITHUB_ENV

      - name: Run integration tests
        run: go test -v ./...

      - name: Build the application
        run: |
          go build -ldflags="-linkmode external -extldflags -static" -o webapp
          echo "Application built successfully"

      - name: Authenticate to Google Cloud via service sccount key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_FOR_GITHUB_ACTIONS }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Build the custom image using Packer
        run: |
          packer init .
          packer build .