name: go project with integration tests

on: pull_request

jobs:
  build-go-project:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.21.6
        uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.21.6"
      - run: go version

      - name: Get all dependencies based on go.mod
        run: go mod download

      - name: Run integration tests
        run: go test -v ./...
        env:
          DB_DSN: ${{ secrets.DB_DSN }}

      - name: Build and run the webapp
        run: |
          go build -o webapp
          ./webapp
        env:
          DB_DSN: ${{ secrets.DB_DSN }}
