name: Webapp workflow

on: fork

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      ENV: "github"
      GO_VERSION: "1.21.6"

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.21.6
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go version

      - name: Get all dependencies based on go.mod
        run: go mod download

      - name: Setup github runner environment variables for integration tests
        run: |
          { 
            echo "DB_HOST=localhost"; 
            echo "DB_PORT=5432"; 
            echo "DB_USER=postgres"; 
            echo "DB_PASSWORD=postgres"; 
            echo "DB_NAME=postgres" 
          } >> $GITHUB_ENV

      - name: Run integration tests
        run: go test -v ./...